import Link from 'next/link';
import {ArrowUpRight,CalendarDays,Users,Compass,FileText,Globe,Heart,Award,Sparkles,Mail,Download} from 'lucide-react';
import {ordered,withYear,type SiteContent} from '@/lib/schema';
import Navigation from './Navigation';
import PatternBackground from './PatternBackground';
import Photo from './Photo';
import Reveal from './Reveal';
import Accordion from './Accordion';
const icons={users:Users,calendar:CalendarDays,compass:Compass,file:FileText,globe:Globe,heart:Heart,award:Award,sparkles:Sparkles};
export function Heading({title,subtitle,index}:{title:string;subtitle:string;index?:string}){return <div className="section-heading"><div className="eyebrow"><span className="short-line"/>{subtitle}{index&&<span className="section-index">{index}</span>}</div><h2>{title}</h2></div>}
function Text({value}:{value:string}){return <div className="rich-text">{value.split('\n\n').map((p,i)=><p key={i}>{p}</p>)}</div>}
export default function PublicSite({content:c,questionnaireOnly=false}:{content:SiteContent;questionnaireOnly?:boolean}){
 const year=(s:string)=>withYear(s,c.settings.applicationYear),h=c.hero,l=c.lcpWord;
 const section=(id:string,children:React.ReactNode,dark=false)=> <section id={id} className={`section ${dark?'navy':''}`} key={id}><div className="container">{children}</div></section>;
 return <div style={{'--navy':c.settings.primaryColor,'--navy-light':c.settings.secondaryColor,'--accent':c.settings.accentColor} as React.CSSProperties}><Navigation content={c} inner={questionnaireOnly}/><main id="main">
 {questionnaireOnly?<section className="section questionnaire-page"><div className="container"><Link href="/#package" className="text-link">Back to application package</Link><Heading title={year(c.questionnaire.title)} subtitle={c.questionnaire.subtitle}/>{c.questionnaire.enabled?<Accordion groups={c.questionnaire.groups} prefix="questionnaire"/>:<p>The questionnaire is not currently available.</p>}</div></section>:<>
 {c.home.enabled&&h.enabled&&<section id="home" className="hero navy"><PatternBackground pattern={c.settings.pattern} imageUrl={h.patternImage}/>{h.backgroundImage&&<div className="hero-background"><Photo src={h.backgroundImage} alt="AIESEC in Suez" priority/><div style={{background:c.settings.primaryColor,opacity:h.overlayOpacity}}/></div>}<span aria-hidden="true" className={`hero-word ${h.backgroundWordSize} word-${h.backgroundWordPosition} ${!h.backgroundWordMobileVisible?'word-hide-mobile':''} ${!h.backgroundWordDesktopVisible?'word-hide-desktop':''}`} style={{opacity:h.backgroundWordOpacity,textTransform:h.backgroundWordUppercase?'uppercase':'none'}}>{h.backgroundWord}</span><div className="container hero-inner"><Reveal><div className="hero-kicker"><span className="short-line"/>{c.home.eyebrow}</div><h1>{year(h.title)}<span>{year(h.subtitle)}</span></h1><div className="hero-lower"><div><p className="hero-lc">{c.settings.lcName}</p><p className="hero-description">{year(h.description)}</p></div><div className="hero-actions">{h.primaryButtonText&&h.primaryButtonUrl&&<Link className="button light" href={h.primaryButtonUrl}>{h.primaryButtonText}<ArrowUpRight size={18}/></Link>}{h.secondaryButtonText&&h.secondaryButtonUrl&&<Link className="button outline" href={h.secondaryButtonUrl}>{h.secondaryButtonText}</Link>}</div></div></Reveal><div className="hero-collage">{ordered(h.heroImages).map((img,i)=><Reveal key={img.id} className={`collage-photo collage-${i}`}><Photo src={img.url} alt={img.alt} priority={i===0}/></Reveal>)}</div><div className="hero-bottom"><span>EXECUTIVE BOARD · {c.settings.applicationYear}</span><span>SCROLL TO EXPLORE <span aria-hidden="true">↓</span></span></div></div></section>}
 {l.enabled&&<section id="lcp-word" className="section lcp-section" style={{background:l.sectionBackground,color:l.textColor}}><PatternBackground pattern={c.settings.pattern} imageUrl={l.patternImage}/><div className="container lcp-grid"><Reveal direction="left" className="lcp-copy"><Heading title={year(l.title)} subtitle={l.subtitle} index="01"/><div className="lcp-message"><Text value={year(l.message)}/>{l.quote&&<blockquote>{year(l.quote)}</blockquote>}<div className="signature">{l.name&&<strong>{l.name}</strong>}<span>{l.role} · {year(l.term)}</span>{l.signatureImage&&<Photo src={l.signatureImage} alt="LCP signature" className="signature-image"/>}</div></div></Reveal><Reveal direction="right" className="lcp-portrait"><div style={{background:l.photoBackground}}><Photo src={l.photoUrl} alt={l.name?`${l.name}, ${l.role}`:'LCP portrait'} position={l.photoObjectPosition}/></div><span className="portrait-caption">{c.settings.lcName} / {c.settings.applicationYear}</span></Reveal></div></section>}
 {c.about.enabled&&section('about',<div className="split"><Reveal><Heading title={year(c.about.title)} subtitle={c.about.subtitle} index="02"/></Reveal><Reveal><Text value={year(c.about.paragraphs)}/><Text value={year(c.about.story)}/>{c.about.quote&&<blockquote>{year(c.about.quote)}</blockquote>}<div className="stats">{ordered(c.about.statistics).map(s=><div key={s.id}><strong>{s.value}</strong><span>{s.label}</span></div>)}</div>{ordered(c.about.values).map(v=><div key={v.id}><h3>{v.title}</h3><p>{v.description}</p></div>)}<div className="about-images">{ordered(c.about.images).map(i=><Photo key={i.id} src={i.url} alt={i.alt}/>)}</div></Reveal></div>)}
 {c.timeline.enabled&&section('timeline',<><Reveal><Heading title={year(c.timeline.title)} subtitle={c.timeline.subtitle} index="03"/></Reveal><div className="timeline">{ordered(c.timeline.events).map((e,i)=>{const Icon=icons[e.icon];return <Reveal key={e.id} className={`timeline-row ${i%2?'right':'left'}`}><div className="timeline-dot"><Icon size={18}/></div><article className="timeline-card"><div className="timeline-meta"><span>{e.date?new Date(`${e.date}T12:00:00Z`).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}):'TO BE ANNOUNCED'}</span>{e.time&&<span>{e.time}</span>}</div><h3>{e.title}</h3><p>{e.description}</p>{e.link&&<Link className="text-link" href={e.link}>View details</Link>}</article></Reveal>})}</div></>,true)}
 {c.commitments.enabled&&section('commitments',<><Heading title={year(c.commitments.title)} subtitle={c.commitments.subtitle} index="04"/><div className="cards commitments">{ordered(c.commitments.items).map(x=>{return <div key={x.id}><article className="card commitment-card"><span className="card-number" aria-hidden="true">{x.number}</span><div className="commitment-copy"><h3>{x.title}</h3>{x.subtitle&&<strong>{x.subtitle}</strong>}<p>{x.description}</p>{x.frequency&&<span className="tag">{x.frequency}</span>}{x.quarter&&<span className="tag">{x.quarter}</span>}{x.link&&<Link href={x.link} className="text-link">Read more</Link>}</div></article></div>})}</div></>)}
 {c.package.enabled&&section('package',<><Heading title={year(c.package.title)} subtitle={c.package.subtitle} index="05"/><div className="package-grid">{ordered(c.package.items).map(x=><Reveal key={x.id}><article className="package-card"><span className="package-number">{x.number}</span><div><h3>{x.link?<Link href={x.link}>{x.title}<ArrowUpRight size={22}/></Link>:x.title}</h3><p>{x.description}</p>{x.subtitle&&<p>{x.subtitle}</p>}</div></article></Reveal>)}</div></>,true)}
 {c.questionnaire.enabled&&section('questionnaire',<><Heading title={year(c.questionnaire.title)} subtitle={c.questionnaire.subtitle} index="06"/><Accordion groups={c.questionnaire.groups} prefix="home-questionnaire"/><Link className="text-link separate-link" href="/questionnaire">Open the full questionnaire <ArrowUpRight size={16}/></Link></>)}
 {c.direction.enabled&&section('direction',<div className="split"><Heading title={year(c.direction.title)} subtitle={c.direction.subtitle} index="07"/><div><span className="tag">{c.direction.instruction}</span><ol className="direction-list">{ordered(c.direction.steps).map((x,i)=><li key={x.id}><span>{String(i+1).padStart(2,'0')}</span><p>{year(x.text)}</p></li>)}</ol></div></div>)}
 {c.functions.enabled&&section('functional',<><Heading title={year(c.functions.title)} subtitle={c.functions.subtitle} index="08"/><Accordion groups={c.functions.groups} prefix="functional" minimal/></>,true)}
 {c.personalAssessment.enabled&&section('assessment',<><Heading title={year(c.personalAssessment.title)} subtitle={c.personalAssessment.subtitle} index="09"/><div className="cards">{ordered(c.personalAssessment.items).map(x=>{const Icon=icons[x.icon];return <article className="card assessment-card" key={x.id}><Icon/><h3>{x.title}</h3><p>{x.description}</p>{x.url?<a href={x.url} target={x.newTab?'_blank':undefined} rel={x.newTab?'noopener noreferrer':undefined} className="text-link">Open assessment <ArrowUpRight size={16}/></a>:<span className="muted">Link coming soon</span>}</article>})}</div></>)}
 {c.cv.enabled&&section('cv',<div className="cv-panel"><Heading title={year(c.cv.title)} subtitle={c.cv.subtitle} index="10"/><div><FileText size={38} strokeWidth={1.2}/><p>{c.cv.description}</p><div className="actions">{c.cv.templateUrl&&<a className="button navy-button" href={c.cv.templateUrl}><Download size={18}/> Download template</a>}{c.cv.exampleUrl&&<a className="button" href={c.cv.exampleUrl}>View example</a>}</div></div></div>)}
 {c.submissionGuidelines.enabled&&section('submission',<><Heading title={year(c.submissionGuidelines.title)} subtitle={c.submissionGuidelines.subtitle} index="11"/><div className="guideline-grid">{ordered(c.submissionGuidelines.cards).map((x,i)=><article className={`guideline${x.id===c.submissionGuidelines.contactCardId?' guideline-with-contacts':''}`} key={x.id}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{x.title}</h3><p>{year(x.description)}</p>{x.id===c.submissionGuidelines.contactCardId&&<div className="contact-strip guideline-contacts">{ordered(c.submissionGuidelines.contacts).map(contact=><a key={contact.id} href={`mailto:${contact.email}`}><Mail size={18}/><span><small>{contact.role}</small>{contact.email}</span></a>)}</div>}</div></article>)}</div></>)}
 {ordered(c.customSections).length>0&&<div id="custom-sections">{ordered(c.customSections).map(x=>section(x.id,<div className="split"><div><Heading title={year(x.title)} subtitle={x.subtitle}/><Text value={year(x.body)}/>{x.linkUrl&&<Link className="text-link" href={x.linkUrl}>{x.linkLabel||'Read more'}</Link>}</div>{x.imageUrl&&<Photo src={x.imageUrl} alt={x.title}/>}</div>,x.dark))}</div>}
 </>}
 </main><footer className="footer navy"><PatternBackground pattern={c.settings.pattern}/><div className="container"><div className="footer-top"><div><strong>{c.footer.title}</strong><p>{year(c.footer.description)}</p></div><nav aria-label="Footer links">{ordered(c.footer.quickLinks).map(x=><Link key={x.id} href={questionnaireOnly&&x.url.startsWith('#')?`/${x.url}`:x.url}>{x.label}</Link>)}</nav><div>{ordered(c.footer.socialLinks).map(x=><a key={x.id} href={x.url} target="_blank" rel="noopener noreferrer">{x.label}</a>)}</div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {c.settings.lcName}</span><span>{c.footer.developerCredit}</span><span>{c.settings.applicationYear}</span></div></div></footer></div>;
}
