import 'server-only';
import {list,put,del} from '@vercel/blob';
import {mkdir,writeFile,readdir,unlink} from 'node:fs/promises';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
export type MediaItem={url:string;pathname:string;filename:string};
export const mediaDirectory=path.join(process.cwd(),'.local','media');
export async function listMedia():Promise<MediaItem[]>{if(process.env.BLOB_READ_WRITE_TOKEN){const all:MediaItem[]=[];let cursor:string|undefined;do{const result=await list({prefix:'media/',limit:1000,cursor});all.push(...result.blobs.map(b=>({url:b.url,pathname:b.pathname,filename:b.pathname.split('/').at(-1)||b.pathname})));cursor=result.hasMore?result.cursor:undefined;}while(cursor);return all;}try{return(await readdir(mediaDirectory)).map(filename=>({url:`/api/media/${filename}`,pathname:filename,filename}));}catch{return [];}}
export function identifyImage(bytes:Uint8Array){if(bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)return {ext:'jpg',mime:'image/jpeg'};if(Buffer.from(bytes.slice(0,8)).equals(Buffer.from([137,80,78,71,13,10,26,10])))return{ext:'png',mime:'image/png'};if(Buffer.from(bytes.slice(0,4)).toString()==='RIFF'&&Buffer.from(bytes.slice(8,12)).toString()==='WEBP')return{ext:'webp',mime:'image/webp'};return null;}
export async function uploadMedia(file:File){if(file.size>4*1024*1024||file.size===0)throw new Error('Choose a JPG, PNG or WebP image up to 4 MB.');const bytes=new Uint8Array(await file.arrayBuffer());const kind=identifyImage(bytes);if(!kind)throw new Error('Only genuine JPG, PNG and WebP files are supported. SVG is disabled for safety.');const name=file.name.replace(/\.[^.]+$/,'').replace(/[^a-zA-Z0-9_-]/g,'-').slice(0,60)||'photo';const filename=`${name}-${randomUUID()}.${kind.ext}`;if(process.env.BLOB_READ_WRITE_TOKEN){const blob=await put(`media/${filename}`,Buffer.from(bytes),{access:'public',addRandomSuffix:false,contentType:kind.mime});return{url:blob.url,pathname:blob.pathname,filename};}if(process.env.VERCEL)throw new Error('Connect Vercel Blob to upload images.');await mkdir(mediaDirectory,{recursive:true});await writeFile(path.join(mediaDirectory,filename),bytes);return{url:`/api/media/${filename}`,pathname:filename,filename};}
export async function deleteMedia(url:string){const found=(await listMedia()).find(m=>m.url===url);if(!found)throw new Error('Image not found in this media library.');if(process.env.BLOB_READ_WRITE_TOKEN)await del(found.url);else await unlink(path.join(mediaDirectory,found.filename));}
