'use client';
import {useId,useState} from 'react';
import {ArrowUp,ArrowDown,Copy,Trash2,Plus,Upload} from 'lucide-react';
import defaults from '@/data/default-content.json';
import Photo from '@/components/Photo';
export type Json=string|number|boolean|null|Json[]|{[key:string]:Json};
type Obj={[key:string]:Json};
const options:Record<string,string[]>={backgroundWordSize:['medium','large','extra-large'],backgroundWordPosition:['top','center','bottom'],photoObjectPosition:['center','top','bottom','left','right'],icon:['users','calendar','compass','file','globe','heart','award','sparkles'],type:['Application Release','DDL','Elections','Selections','Announcement','Interview','Custom'],repeat:['repeat','no-repeat'],blendMode:['normal','overlay','soft-light','multiply','screen']};
const labels:Record<string,string>={backgroundWord:'Hero Background Word',backgroundWordOpacity:'Background word opacity (0–1)',backgroundWordSize:'Background word size',backgroundWordPosition:'Background word position',backgroundWordUppercase:'Uppercase background word',backgroundWordMobileVisible:'Show background word on mobile',backgroundWordDesktopVisible:'Show background word on desktop',primaryButtonUrl:'Primary button URL',secondaryButtonUrl:'Secondary button URL',photoUrl:'LCP photo',name:'LCP full name',message:'LCP message',url:'URL',newTab:'Open in a new tab',inMore:'Place in More menu',ogTitle:'Open Graph title',ogDescription:'Open Graph description',lcName:'LC name',seoTitle:'SEO title',seoDescription:'SEO description',developerCredit:'Developer credit',contactCardId:'Guideline containing submission contacts'};
export const label=(key:string)=>labels[key]||key.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase());
const imageKeys=new Set(['photoUrl','imageUrl','backgroundImage','patternImage','signatureImage','logo','favicon','socialImage']);
const longKeys=new Set(['description','message','body','paragraphs','story','quote','text','seoDescription','ogDescription']);
const base={id:'',enabled:true,order:0};
const templates:Record<string,Obj>={
 customSections:{...base,title:'New section',subtitle:'',body:'',imageUrl:'',linkLabel:'',linkUrl:'',dark:false},
 images:{...base,url:'',alt:'New photo'},heroImages:{...base,url:'',alt:'New photo'},
 statistics:{...base,value:'',label:''},values:{...base,title:'New value',description:''},
 questions:{...base,text:''},steps:{...base,text:''},
 quickLinks:{...base,label:'New link',url:''},socialLinks:{...base,label:'New link',url:''}
};
function seedFor(path:string){const pieces=path.split('.').filter(p=>!/^\d+$/.test(p));let cursor:unknown=defaults;for(const p of pieces){if(Array.isArray(cursor))cursor=cursor[0];cursor=(cursor as Record<string,unknown>)?.[p];}if(Array.isArray(cursor)&&cursor.length)return structuredClone(cursor[0]) as Obj;return structuredClone(templates[pieces.at(-1)||'']||{...base,title:'New item'});}
function cloneIds(value:Json):Json{if(Array.isArray(value))return value.map(cloneIds);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,k==='id'?crypto.randomUUID():cloneIds(v)]));return value;}
export async function upload(file:File){if(file.size>4*1024*1024)throw new Error('Choose an image up to 4 MB.');const body=new FormData();body.set('file',file);const response=await fetch('/api/media',{method:'POST',body});const data=await response.json();if(!response.ok)throw new Error(data.error||'Upload failed.');return data as {url:string;filename:string};}
function ImageUpload({value,onChange}:{value:string;onChange:(value:Json)=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <><div className="field-upload"><label className="mini-button"><Upload size={14}/>{busy?'Uploading…':'Upload image'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} style={{maxWidth:210}} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');try{const result=await upload(file);onChange(result.url);}catch(e){setError(e instanceof Error?e.message:'Upload failed.');}finally{setBusy(false);}}}/></label></div>{error&&<span className="alert error" role="alert">{error}</span>}{value&&<Photo src={value} alt="Selected image preview"/>}</>}
export default function Fields({value,onChange,path=''}:{value:Json;onChange:(value:Json)=>void;path?:string}){
 const id=useId();
 if(Array.isArray(value)){
  const update=(index:number,item:Json)=>onChange(value.map((v,i)=>i===index?item:v));
  const normalized=(items:Json[])=>items.map((v,i)=>typeof v==='object'&&v&&!Array.isArray(v)?{...v,order:i}:v);
  return <div className="repeatable"><div className="repeatable-heading"><h3>{label(path.split('.').at(-1)||'Items')} <span className="muted">({value.length})</span></h3><button type="button" className="mini-button" onClick={()=>onChange(normalized([...value,cloneIds(seedFor(path))]))}><Plus size={14}/> Add</button></div>{!value.length&&<p className="admin-note">No items yet. Add one to include it on the website.</p>}{value.map((entry,index)=>{const obj=entry as Obj;return <details className="repeat-item" key={String(obj.id||index)}><summary>{String(obj.title||obj.label||obj.alt||obj.role||obj.text||`Item ${index+1}`).slice(0,100)}{obj.enabled===false?' · Hidden':''}</summary><div className="repeat-controls"><button className="mini-button" type="button" disabled={index===0} aria-label="Move item up" onClick={()=>{const next=[...value];[next[index],next[index-1]]=[next[index-1],next[index]];onChange(normalized(next));}}><ArrowUp size={14}/> Up</button><button className="mini-button" type="button" disabled={index===value.length-1} aria-label="Move item down" onClick={()=>{const next=[...value];[next[index],next[index+1]]=[next[index+1],next[index]];onChange(normalized(next));}}><ArrowDown size={14}/> Down</button><button className="mini-button" type="button" onClick={()=>{const next=[...value];next.splice(index+1,0,cloneIds(entry));onChange(normalized(next));}}><Copy size={14}/> Duplicate</button><button className="mini-button danger" type="button" onClick={()=>{if(confirm('Delete this item? The change will be applied when you save.'))onChange(normalized(value.filter((_,i)=>i!==index)));}}><Trash2 size={14}/> Delete</button></div><Fields value={entry} onChange={v=>update(index,v)} path={`${path}.${index}`}/></details>})}</div>;
 }
 if(value&&typeof value==='object')return <div className="admin-fields">{Object.entries(value).map(([key,item])=>{if(key==='order')return null;if(key==='contactCardId'&&Array.isArray(value.cards))return <label className="field full" key={key}><span className="field-label">Guideline containing submission contacts</span><select value={String(item)} onChange={e=>onChange({...value,contactCardId:e.target.value})}>{value.cards.map(card=>{const c=card as Obj;return <option key={String(c.id)} value={String(c.id)}>{String(c.title)}</option>;})}</select><span className="field-help">Contacts stay inside this guideline when the cards are reordered or hidden.</span></label>;const fieldPath=path?`${path}.${key}`:key;if(item&&typeof item==='object'&&!Array.isArray(item))return <fieldset className="nested-fields" key={key}><legend>{label(key)}</legend><Fields value={item} path={fieldPath} onChange={v=>onChange({...value,[key]:v})}/></fieldset>;return <Fields key={key} value={item} path={fieldPath} onChange={v=>onChange({...value,[key]:v})}/>;})}</div>;
 const key=path.split('.').at(-1)||'value',image=imageKeys.has(key)||(key==='url'&&/Images|\.images\./.test(path));
 if(typeof value==='boolean')return <label className="field-check"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/>{label(key)}</label>;
 const url=/Url$|^url$|^link$/.test(key)||image;
 return <div className={`field ${longKeys.has(key)||image?'full':''}`}><label htmlFor={id}>{label(key)}</label>{options[key]?<select id={id} value={String(value)} onChange={e=>onChange(e.target.value)}>{options[key].map(o=><option key={o} value={o}>{label(o)}</option>)}</select>:longKeys.has(key)?<textarea id={id} value={String(value??'')} onChange={e=>onChange(e.target.value)} rows={key==='message'?8:4}/>:<input id={id} type={typeof value==='number'?'number':key==='date'?'date':key==='email'?'email':/Color$|Background$/.test(key)&&!image?'color':'text'} step={typeof value==='number'?0.01:undefined} min={typeof value==='number'?0:undefined} max={typeof value==='number'?1:undefined} value={value??''} onChange={e=>onChange(typeof value==='number'?Number(e.target.value):e.target.value)} readOnly={key==='id'}/>}{image&&<ImageUpload value={String(value||'')} onChange={onChange}/>}<span className="field-help">{key==='id'?'Stable identifier; custom section IDs can be linked as #identifier.':key==='term'||key==='applicationYear'?'Use {year} in titles and text to follow the global application year.':url?'HTTPS URL, local path, section anchor or mailto link. Leave blank when unavailable.':key==='opacity'||key.endsWith('Opacity')?'0 = transparent, 1 = fully visible.':''}</span></div>;
}
